# Generated by Django 4.1.1 on 2022-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_activation_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
