# Generated by Django 4.1.1 on 2022-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
