# Generated by Django 4.1.1 on 2022-09-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_url_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation',
        ),
    ]
