# Generated by Django 4.1.1 on 2022-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_url_link_user_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
